### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by Pyroptical** [Soliel/Beat-Saber-Twitch-Integration#12]
When users are requesting songs despite using text with correct spelling form the title,some songs will read back the error invalid request,it can be mitigated by using the song id instead but viewers were a little frustrated by this. see here for clip ( https://clips.twitch.tv/HardCrazyPartridgeYouWHY ) equally the text parsing when it does work can be a bit off for example requesting "song" will get you the skyrim theme, and requesting "Numb" will get you we are number one test will get you sum 41 the hell.

**Comment by Soliel** [comment]
This is actually a limitation with Beatsaver, the plugin sends the request to beatsaver and then lets them do the searching. I've been working with them to improve this but for now, it's stuck x.x. However if people want EXACT matches, tell them to wrap it in quotations example numb - returns we are number 1: [example](https://i.imgur.com/GhuT8Ws.png). but if I put quotations around it it brings the correct result: [example](https://i.imgur.com/NlO7BJZ.png)

so unfortunately not much I can do about this here!
