### ISSUE TITLE
Feature Request: Go to normal end screen before showing next song

### ISSUE THREAD

**Issue by FromenActual** [Soliel/Beat-Saber-Twitch-Integration#14]
Usually after a song is finished (complete/fail/etc.), the plugin brings the player straight to the next song instead of the normal end of song screen (example clip [here](https://clips.twitch.tv/HeartlessLightMuleHoneyBadger). Would be nice to show the normal end screen first to allow the player to see their scores or even restart if they fail a song.

**Comment by Soliel** [comment]
This was present in the old version of the plugin and I kinda miss it too. the reason for it not showing is because of the way I handle UI code. since I didn't wanna rewrite the UI from scratch delaying the release I compromised. Needless to say it is coming back

**Comment by Soliel** [comment]
This is addressed in the new version of the plugin
