### ISSUE TITLE
Suggestions: Bigger Twitch integration

### ISSUE THREAD

**Issue by ToRRent1812** [Soliel/Beat-Saber-Twitch-Integration#17]
I have few suggestions regarding plugin:
- There is no results screen after completing the track, can You bring that back?
- Let us choose difficulty at some point
- Show, who requested the song

That's it :D

**Comment by Soliel** [comment]
Most of these are actually related to a single big rewrite I needed to do since the 11.1 update so soon™

**Comment by Soliel** [comment]
Fixed in the UI and BotRefactor updates combined.
