### ISSUE TITLE
Scores not submitting

### ISSUE THREAD

**Issue by Syilvemce** [Soliel/Beat-Saber-Twitch-Integration#22]
i got this cool little bug where when i play a song off request queue in twitch integration, and fail the song, and go back to my song list in solo like normal and play a song and beat it, itll send me back to the main menu and my score wont submit

**Comment by Soliel** [comment]
This has been addressed in the most recent beatsaber update as the root problem stemmed from how they handled scene switching. Once the 0.12.0 update of bsr comes out this will be taken care of.
