### ISSUE TITLE
Commands in twitch are doing nothing....

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Soliel/Beat-Saber-Twitch-Integration#26]
I have installed the mod files in the directory, set up the plugin's XML file, possibly wrong as theres not really any instructions with it. But typing !BSR in my chat with the game running makes nothing happen. 

The mod is installed in beatsaber file location. Some people have said something about some IRC or something? I have no bots in my channel or anything, so how would the plugin inside beatsaber talk to my twitch channel. Please help.

**Comment by Soliel** [comment]
This is a better question for the BeatSaber Modding Group #Support Channel. If you aren't in the modding group message me on discord at Soliel#5150 for help. Though wait a few days as I'm trying to get the plugin updated for 0.12.0

**Comment by TheBitcoinBaron** [comment]
Hi sorry but I dont know what you are talking about with #Support channel, The only github options on the top are code / issues / pull requests / projects wiki and insights. I dont have discord.
