### ISSUE TITLE
Followers only

### ISSUE THREAD

**Issue by jaredcat** [Soliel/Beat-Saber-Twitch-Integration#3]
This is really cool, but could you add in a followers only mode?  
I have an example here: https://github.com/UpDownLeftDie/SongBouncer/blob/master/index.js#L94

**Comment by Soliel** [comment]
Another developer and I have been working on improving the twitch bot part of the plugin and this falls in that purview, so you should be seeing this soon~

**Comment by jaredcat** [comment]
Just curious if this was going to be included in the new rewrite?

**Comment by jaredcat** [comment]
I wrote some preliminary code: https://github.com/UpDownLeftDie/Beat-Saber-Twitch-Integration/tree/BotRefactor
note that i don't know C# so sorry if this is junk but I hope it helps in some way.
